package cmd

var fileExtentions = map[string]string{
  ".txt": "Text document",
  ".env": "Environment variable file",
  ".conf": "Generic configuration file",
  ".cfg": "Generic configuration file",
  ".kdb": "Keypass database file",
  ".kdbx": "Keybase database file in XML",
  ".ini": "Initialization file for program settings",
  ".inc": "Generic configuration file with headers, declarations, data, etc",
  ".php": "Hypertext preprocessor file,
  ".py": "Python file",
  ".js": "JavaScript file",
  ".json": "JavaScript Object Notation file",
  ".properties":"Key-value pair file with configurable parameters",
  ".pem": "Privacy enhanced mail file",
  ".yaml": "Yet another markup language file",
  ".yml": "Yet another markup language file",
  ".csv": "Comma-seperated values file",
  ".xml": "Extensible markup languagee file",
  ".zip": "ZIP compressed file",
  ".tar": "TAR compressed file",
  ".tgz": "GNU zip compressed TAR archive",
  ".tar.gz": "GNU zip compressed TAR archive",
  ".sh": "Bash script",
  ".bak": "Backup file",
  ".7z": "7-ZIP compressed file",
  ".rar": "RAR file",
  ".z": "Z compressed file",
  ".db": "Database file",
  ".sql": "SQL database file",
  ".email": "Outlook e-mail message file",
  ".eml": "Generic e-mail message file",
  ".emlx": "Apple Mail e-mail message file",
  ".msg": "Microsoft Outlook e-mail message file",
  ".bat": "Windows Batch file",
  ".ps1": "Windows PowerShell file",
  ".tf": "Terraform configuration file",
  ".xls": "Microsoft Excel file",
  ".xlsm": "Microsoft Excel file with macros",
  ".xlsx": "Microsoft Excel Open XML spreadsheet file",
  ".doc": "Microsoft Word file",
  ".pdf": "Portable document format file",
  ".asp": "Active server page file",
  ".gz": "GNU zip compressed file",
  ".gzip": "GNU zip compressed file",
  ".rb": "Ruby file",
  ".go": "Golang file",
  ".java": "Java file",
  ".jar": "Java classes archive file",
}
