name: testing matrix builds
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: "actions/setup-go@v3"
        with:
          go-version: ${{ matrix.go-version }}
      - uses: "actions/checkout@v3"
        with:
          token: ${{ github.token }}
      - run: go build .

